# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Start jksb

on:
  workflow_dispatch:
  schedule:
    - cron: '27 18,19,21 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#    - uses: actions/download-artifact@v3
#      with:
#        name: Download signed.json
    - name: Start jksb Direct
#      if: always()
      env:
        mail_id: ${{secrets.mail_id}}
        mail_pd: ${{secrets.mail_pd}}
        processing_pool: ${{secrets.processing_pool}}
      run: |
        python Application.py "$mail_id" "$mail_pd" "$processing_pool"
#    - uses: actions/upload-artifact@v3
#      if: always()
#      with:
#        name: Upload signed.json
#        path: signed.json
